/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Menadzer;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logika.Controler;
import nit.NitOsluskivanjeMenadzer;
import sesija.Session;

/**
 *
 * @author duler
 */
public class GlavnaFormaMenadzer extends javax.swing.JFrame {

    NitOsluskivanjeMenadzer nit;
    /**
     * Creates new form GlavnaFormaMenadzer
     */
    public GlavnaFormaMenadzer() {
        initComponents();
    }

    public GlavnaFormaMenadzer(Menadzer m) {
        initComponents();
        lblMenadzer.setText("Prijavljeni menadzer: " + m.toString());
        
//        nit= new NitOsluskivanjeMenadzer(this, Session.getInstance().getSocket());
//       
//        nit.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenadzer = new javax.swing.JLabel();
        btnOdjavi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiKreirajNoviTim = new javax.swing.JMenuItem();
        jmiPretraziTimove = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiKreirajNovogTrenera = new javax.swing.JMenuItem();
        jmiPretraziTrenere = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiUpisiIgracaUKlub = new javax.swing.JMenuItem();
        jmiIspisiIgracaIzKluba = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenadzer.setText("Prijavljeni menadzer:");

        btnOdjavi.setText("Odjavi se");
        btnOdjavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviActionPerformed(evt);
            }
        });

        jMenu1.setText("Timovi");

        jmiKreirajNoviTim.setText("Kreiraj novi tim");
        jmiKreirajNoviTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreirajNoviTimActionPerformed(evt);
            }
        });
        jMenu1.add(jmiKreirajNoviTim);

        jmiPretraziTimove.setText("Pretrazi timove");
        jmiPretraziTimove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziTimoveActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPretraziTimove);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Treneri");

        jmiKreirajNovogTrenera.setText("Kreiraj novog trenera");
        jmiKreirajNovogTrenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreirajNovogTreneraActionPerformed(evt);
            }
        });
        jMenu2.add(jmiKreirajNovogTrenera);

        jmiPretraziTrenere.setText("Pretrazi trenere");
        jmiPretraziTrenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziTrenereActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPretraziTrenere);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Igraci");

        jmiUpisiIgracaUKlub.setText("Upisi igraca u klub");
        jmiUpisiIgracaUKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUpisiIgracaUKlubActionPerformed(evt);
            }
        });
        jMenu3.add(jmiUpisiIgracaUKlub);

        jmiIspisiIgracaIzKluba.setText("Ispisi igraca iz kluba");
        jmiIspisiIgracaIzKluba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIspisiIgracaIzKlubaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiIspisiIgracaIzKluba);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(lblMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnOdjavi)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenadzer)
                    .addComponent(btnOdjavi))
                .addContainerGap(432, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUpisiIgracaUKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUpisiIgracaUKlubActionPerformed
        UpisiIgracaUKlubMenadzerForma uk = new UpisiIgracaUKlubMenadzerForma(this, true);
        
        uk.setVisible(true);
    }//GEN-LAST:event_jmiUpisiIgracaUKlubActionPerformed

    private void jmiIspisiIgracaIzKlubaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIspisiIgracaIzKlubaActionPerformed
        IspisiIgracaIzKlubaMenadzerForma ii = new IspisiIgracaIzKlubaMenadzerForma(this, true);
        ii.setVisible(true);
    }//GEN-LAST:event_jmiIspisiIgracaIzKlubaActionPerformed

    private void jmiKreirajNoviTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreirajNoviTimActionPerformed
        KreirajNoviTimMenadzerForma knf = new KreirajNoviTimMenadzerForma(this, true);
        knf.setVisible(true);
        
    }//GEN-LAST:event_jmiKreirajNoviTimActionPerformed

    private void jmiKreirajNovogTreneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreirajNovogTreneraActionPerformed
        JDialog tmf = new TrenerMenadzerForma(this, true);
        tmf.setVisible(true);
        Session.getInstance().setUseCase(UseCase.UC_NEW_TRAINER);
    }//GEN-LAST:event_jmiKreirajNovogTreneraActionPerformed

    private void jmiPretraziTimoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziTimoveActionPerformed
        JDialog ptmf = new PretraziTimoveMenadzerForma(this, true);
        ptmf.setVisible(true);
    }//GEN-LAST:event_jmiPretraziTimoveActionPerformed

    private void jmiPretraziTrenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziTrenereActionPerformed
        JDialog ptrmf = new PretraziTrenereMenadzerForma(this, true);
        ptrmf.setVisible(true);
    }//GEN-LAST:event_jmiPretraziTrenereActionPerformed

    private void btnOdjaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviActionPerformed
        // TODO add your handling code here:
        try {
           boolean odjavio= Controler.getInstanca().logout();
          if(odjavio)
           JOptionPane.showMessageDialog(this, "Uspesno ste se odjavili sa sistema!");
            System.exit(0);
            
        } catch (Exception ex) {
            System.out.println("Greska kod odjavljivanja sa sistema");
            Logger.getLogger(GlavnaFormaMenadzer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOdjaviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaMenadzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaFormaMenadzer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjavi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiIspisiIgracaIzKluba;
    private javax.swing.JMenuItem jmiKreirajNoviTim;
    private javax.swing.JMenuItem jmiKreirajNovogTrenera;
    private javax.swing.JMenuItem jmiPretraziTimove;
    private javax.swing.JMenuItem jmiPretraziTrenere;
    private javax.swing.JMenuItem jmiUpisiIgracaUKlub;
    private javax.swing.JLabel lblMenadzer;
    // End of variables declaration//GEN-END:variables

   
    
    public void ugasiGlavnuFormu() {
        try {
            JOptionPane.showMessageDialog(this, "Server je ugasen!");
            Session.getInstance().getSocket().close();
            nit.interrupt();
          /* System.exit(0);*/
          this.dispose();
//            LoginForm nova= new LoginForm();
//            nova.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GlavnaFormaTrener.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
