/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Trener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Controler;
import nit.NitOsluskivanjeTrener;
import sesija.Session;

/**
 *
 * @author duler
 */
public class GlavnaFormaTrener extends javax.swing.JFrame {

    NitOsluskivanjeTrener nit;
    /**
     * Creates new form GlavnFormaTrener
     */
    public GlavnaFormaTrener() {
        initComponents();
    }

    GlavnaFormaTrener(Trener t) {
        initComponents();
        lblTrener.setText("Prijavljeni trener: " + t.toString());
        
//        nit= new NitOsluskivanjeTrener(this,Session.getInstance().getSocket());
//       
//        nit.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        lblTrener = new javax.swing.JLabel();
        btnOdjavi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiPretraziSvojeIgrace = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiPretraziUtakmice = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiEvidentirajStatistiku = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTrener.setText("Prijavljeni trener:");

        btnOdjavi.setText("Odjavi se");
        btnOdjavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviActionPerformed(evt);
            }
        });

        jMenu2.setText("Igraci");

        jmiPretraziSvojeIgrace.setText("Pretrazi svoje igrace");
        jmiPretraziSvojeIgrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziSvojeIgraceActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPretraziSvojeIgrace);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Utakmice");

        jmiPretraziUtakmice.setText("Pretrazi utakmice");
        jmiPretraziUtakmice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziUtakmiceActionPerformed(evt);
            }
        });
        jMenu4.add(jmiPretraziUtakmice);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Statistika");

        jmiEvidentirajStatistiku.setText("Evidentiraj statistiku");
        jmiEvidentirajStatistiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEvidentirajStatistikuActionPerformed(evt);
            }
        });
        jMenu5.add(jmiEvidentirajStatistiku);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(lblTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdjavi)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrener)
                    .addComponent(btnOdjavi))
                .addContainerGap(433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEvidentirajStatistikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEvidentirajStatistikuActionPerformed
        EvidentirajStatistikuTrenerForma es = new EvidentirajStatistikuTrenerForma(this, true);
        es.setVisible(true);
    }//GEN-LAST:event_jmiEvidentirajStatistikuActionPerformed

    private void jmiPretraziSvojeIgraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziSvojeIgraceActionPerformed
        PretragaSvojihIgraca psi = new PretragaSvojihIgraca(this, true);
        psi.setVisible(true);
    }//GEN-LAST:event_jmiPretraziSvojeIgraceActionPerformed

    private void jmiPretraziUtakmiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziUtakmiceActionPerformed
        PretraziUtakmiceTrenerF putf = new PretraziUtakmiceTrenerF(this, true);
        putf.setVisible(true);
    }//GEN-LAST:event_jmiPretraziUtakmiceActionPerformed

    private void btnOdjaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviActionPerformed
        // TODO add your handling code here:
        try {
            boolean odjavio= Controler.getInstanca().logout();
            if(odjavio)
            JOptionPane.showMessageDialog(this, "Uspesno ste se odjavili sa sistema!");
            System.exit(0);

        } catch (Exception ex) {
            System.out.println("Greska kod odjavljivanja sa sistema");
            Logger.getLogger(GlavnaFormaMenadzer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOdjaviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaTrener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaTrener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaTrener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaFormaTrener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaFormaTrener().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjavi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiEvidentirajStatistiku;
    private javax.swing.JMenuItem jmiPretraziSvojeIgrace;
    private javax.swing.JMenuItem jmiPretraziUtakmice;
    private javax.swing.JLabel lblTrener;
    // End of variables declaration//GEN-END:variables

    public void ugasiGlavnuFormu() {
        try {
            JOptionPane.showMessageDialog(this, "Server je ugasen!");
            Session.getInstance().getSocket().close();
            nit.interrupt();
          /* System.exit(0);*/
          this.dispose();
//            LoginForm nova= new LoginForm();
//            nova.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GlavnaFormaTrener.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
