/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Igrac;
import domen.Pozicija;
import domen.Sport;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logika.Controler;
import modeli.ModelTabeleIgraci;
import domen.IGeneralEntity;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author duler
 */
public class IspisiIgracaIzKlubaMenadzerForma extends javax.swing.JDialog {

    /**
     * Creates new form IspisiIgracaIzKlubaMenadzerForma
     */
    public IspisiIgracaIzKlubaMenadzerForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        napuniKomboSportova();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbSport = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaIgraci = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        btnPrimeniFiltere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ispisivanje igraca iz kluba"));

        jLabel1.setText("Sport:");

        cmbSport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Prezime:");

        tabelaIgraci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaIgraci);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnPrimeniFiltere.setText("Primeni filtere");
        btnPrimeniFiltere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeniFiltereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbSport, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnPrimeniFiltere, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrimeniFiltere, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeniFiltereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeniFiltereActionPerformed
        Sport sport = (Sport) cmbSport.getSelectedItem();
        String prezime = txtPrezime.getText().trim();

        Igrac igrac = new Igrac();
        igrac.setPozicija(new Pozicija());
        igrac.getPozicija().setSport(sport);
        igrac.setPrezime(prezime);
        //igrac.setDatumRodjenja(new Date());
        ArrayList<Igrac> igraci = new ArrayList<>();
        try {
            igraci = Controler.getInstanca().pronadjiIgrace((igrac));
        } catch (Exception ex) {
            Logger.getLogger(IspisiIgracaIzKlubaMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        ModelTabeleIgraci mti = (ModelTabeleIgraci) tabelaIgraci.getModel();
        mti.setListaIgraca(igraci);
        mti.fireTableDataChanged();
        
        if(igraci.size() >= 1) {
            JOptionPane.showMessageDialog(this, "Sistem je nasao igrace po zadatoj vrednosti");


        }
        else {
            JOptionPane.showMessageDialog(this, "Sistem nije nasao igrace po zadatoj vrednosti");

        }
    }//GEN-LAST:event_btnPrimeniFiltereActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

          int row = tabelaIgraci.getSelectedRow();
        if(row > -1){
            ModelTabeleIgraci mttr = (ModelTabeleIgraci) tabelaIgraci.getModel();
            Igrac igrac = mttr.getIgrac(row);
            JDialog atmf = new AzurirajIgracaMenadzerForma(null, rootPaneCheckingEnabled, igrac);
            JOptionPane.showMessageDialog(this, "Sistem je vratio igraca koji ima ID " + igrac.getSifraIgraca());

            atmf.setVisible(true);
        }
//        ModelTabeleIgraci mti = (ModelTabeleIgraci) tabelaIgraci.getModel();
//        int row = tabelaIgraci.getSelectedRow();
//        if (row < 0) {
//            JOptionPane.showMessageDialog(this, "Niste selektovali nijednog igraca!");
//            return;
//        }
//        Igrac igrac = (Igrac) mti.getListaIgraca().get(row);
//        boolean ispisanIzKluba = false;
//        try {
//            igrac.setDaLiJeAktivanIgrac(false);
//            ispisanIzKluba = Controler.getInstanca().azurirajIgraca(igrac);
//        } catch (Exception ex) {
//            Logger.getLogger(IspisiIgracaIzKlubaMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        if (ispisanIzKluba) {
//            JOptionPane.showMessageDialog(this, "Uspesno ste izbrisali ispisali igraca iz kluba!");
//            mti.obrisiRed(row);
//            mti.fireTableDataChanged();
//        } else {
//            JOptionPane.showMessageDialog(this, "Niste izbrisali igraca iz kluba!");
//        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IspisiIgracaIzKlubaMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IspisiIgracaIzKlubaMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IspisiIgracaIzKlubaMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IspisiIgracaIzKlubaMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IspisiIgracaIzKlubaMenadzerForma dialog = new IspisiIgracaIzKlubaMenadzerForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnPrimeniFiltere;
    private javax.swing.JComboBox cmbSport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaIgraci;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        Sport sport = (Sport) cmbSport.getSelectedItem();
        String prezime = txtPrezime.getText().trim();

        Igrac igrac = new Igrac();
        igrac.setPozicija(new Pozicija());
        igrac.getPozicija().setSport(sport);
        igrac.setPrezime(prezime);
        ArrayList<Igrac> listaIgraca = new ArrayList<>();
        try {
            listaIgraca = Controler.getInstanca().pronadjiIgrace((Igrac) igrac);
        } catch (Exception ex) {
            Logger.getLogger(IspisiIgracaIzKlubaMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        ModelTabeleIgraci mti = new ModelTabeleIgraci(listaIgraca);
        tabelaIgraci.setModel(mti);
    }

    private void napuniKomboSportova() {
        ArrayList<Sport> listaSportova = new ArrayList<>();
        cmbSport.removeAllItems();
        try {
            listaSportova = Controler.getInstanca().vratiSveSportove();
        } catch (Exception ex) {
            Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(listaSportova);
        for (IGeneralEntity sport : listaSportova) {
            cmbSport.addItem(sport);
        }
    }
}
