/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.IGeneralEntity;
import domen.Igrac;
import domen.StatistikaIgracaSaUtakmice;
import domen.Tim;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logika.Controler;
import modeli.ModelTabeleIgraci;
import modeli.ModelTabeleIgraciStatistika;
import sesija.Session;

/**
 *
 * @author duler
 */
public class PretragaSvojihIgraca extends javax.swing.JDialog {

    /**
     * Creates new form PretragaSvojihIgraca
     */
    public PretragaSvojihIgraca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        popuniKomboTim();
        //popuniTabeluIgraca();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIgraci = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbTim = new javax.swing.JComboBox();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblIgraci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIgraci);

        jLabel2.setText("Tim:");

        cmbTim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTimItemStateChanged(evt);
            }
        });

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(cmbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTimItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED ) {
            System.out.println(evt.getSource());
            popuniTabeluIgraca();
        }


    }//GEN-LAST:event_cmbTimItemStateChanged

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int row = tblIgraci.getSelectedRow();
        if (row > -1) {
            ModelTabeleIgraci mti = (ModelTabeleIgraci) tblIgraci.getModel();
            Igrac igrac = mti.getIgrac(row);
            JDialog atmf = new PregledajIgracaTrenerForma(null, rootPaneCheckingEnabled, igrac);
            JOptionPane.showMessageDialog(this, "Odabrani igrac ima ID " + igrac.getSifraIgraca());

            atmf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Igrac ne moze biti prikazan!");

        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaSvojihIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaSvojihIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaSvojihIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaSvojihIgraca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretragaSvojihIgraca dialog = new PretragaSvojihIgraca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JComboBox cmbTim;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIgraci;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboTim() {
        ArrayList<Tim> listaTimova = new ArrayList<>();
        cmbTim.removeAllItems();

        try {
            listaTimova = Controler.getInstanca().vratiTimoveTrenera(Session.getInstance().getTrener());
        } catch (Exception ex) {
            Logger.getLogger(EvidentirajStatistikuTrenerForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (IGeneralEntity ekipa : listaTimova) {
            cmbTim.addItem(ekipa);
        }
    }

    private void popuniTabeluIgraca() {
        Tim tim = (Tim) cmbTim.getSelectedItem();
        if (tim != null) {
            try {
                Igrac igrac = new Igrac();
                igrac.setTim((Tim) cmbTim.getSelectedItem());
                ArrayList<Igrac> listaIgraca = Controler.getInstanca().pronadjiIgrace(igrac);
                System.out.println(listaIgraca.size());
                ModelTabeleIgraci mti = new ModelTabeleIgraci(listaIgraca);
                tblIgraci.setModel(mti);
                if (listaIgraca.size() > 0) {
                    JOptionPane.showMessageDialog(this, "Sistem je nasao igrace po zadatoj vrednosti");
                }
                else {
                    JOptionPane.showMessageDialog(this, "Igraci nisu pronadjeni!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Igraci nisu pronadjeni!");
            }
        }
    }

}
