/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Tim;
import domen.Utakmica;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logika.Controler;
import modeli.ModelTabeleUtakmice;

/**
 *
 * @author duler
 */
public class PretraziUtakmiceTrenerF extends javax.swing.JDialog {

    /**
     * Creates new form PretraziUtakmiceTrenerF
     */
    public PretraziUtakmiceTrenerF(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        popuniTabelu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUtakmice = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        txtProtivnik = new javax.swing.JTextField();
        btnPrimeniFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretrazi utakmice"));

        jLabel1.setText("Protivnik:");

        tblUtakmice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUtakmice);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnPrimeniFilter.setText("Primeni filter");
        btnPrimeniFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeniFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtProtivnik, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnPrimeniFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalji)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProtivnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrimeniFilter))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int row = tblUtakmice.getSelectedRow();
        if(row > -1){
            ModelTabeleUtakmice mtu = (ModelTabeleUtakmice) tblUtakmice.getModel();
            Utakmica utakmica = mtu.getUtakmica(row);
            JDialog atmf = new PregledajUtakmicuTrenerForma(null, rootPaneCheckingEnabled, utakmica);
            JOptionPane.showMessageDialog(this, "Odabrana utakmica ima ID " + utakmica.getSifraUtakmice());

            atmf.setVisible(true);
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnPrimeniFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeniFilterActionPerformed

        String protivnik = txtProtivnik.getText().trim();

        ArrayList<Utakmica> listaUtakmica = new ArrayList<>();
        try {
            System.out.println("Trener: " + Controler.getInstanca().getTrener());
            System.out.println("Pre pozivanja controlera");

            Utakmica utakmica = new Utakmica();
            utakmica.setTim(new Tim());
            utakmica.getTim().setTrener(Controler.getInstanca().getTrener());
            utakmica.setNazivProtivnika(txtProtivnik.getText());
            listaUtakmica = Controler.getInstanca().vratiOdabraneUtakmiceTrenera(utakmica);
        } catch (Exception ex) {
            Logger.getLogger(PretraziTimoveMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        ModelTabeleUtakmice mtu = new ModelTabeleUtakmice(listaUtakmica);
        tblUtakmice.setModel(mtu);

        mtu.fireTableDataChanged();

        System.out.println("Broj utakmica: " + listaUtakmica.size());

        if(listaUtakmica.size() >= 1) {
            JOptionPane.showMessageDialog(this, "Sistem je nasao utakmice po zadatoj vrednosti");

        }
        else {
            JOptionPane.showMessageDialog(this, "Sistem nije nasao utakmice po zadatoj vrednosti");

        }
    }//GEN-LAST:event_btnPrimeniFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziUtakmiceTrenerF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziUtakmiceTrenerF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziUtakmiceTrenerF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziUtakmiceTrenerF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretraziUtakmiceTrenerF dialog = new PretraziUtakmiceTrenerF(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void popuniTabelu() {
        ArrayList<Utakmica> listaUtakmica = new ArrayList<>();
        try {
            System.out.println("Trener: " + Controler.getInstanca().getTrener());
            System.out.println("Pre pozivanja controlera");
            Utakmica u = new Utakmica();
            listaUtakmica = Controler.getInstanca().vratiUtakmiceTrenera(Controler.getInstanca().getTrener());
        } catch (Exception ex) {
            Logger.getLogger(PretraziTimoveMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        ModelTabeleUtakmice mtu = new ModelTabeleUtakmice(listaUtakmica);
        tblUtakmice.setModel(mtu);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnPrimeniFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUtakmice;
    private javax.swing.JTextField txtProtivnik;
    // End of variables declaration//GEN-END:variables
}
