/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Profil;
import domen.Sport;
import domen.Trener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logika.Controler;
import domen.IGeneralEntity;
import java.util.logging.Level;
import java.util.logging.Logger;
import modeli.ModelTabeleTreneri;

/**
 *
 * @author duler
 */
public class TrenerMenadzerForma extends javax.swing.JDialog {

    /**
     * Creates new form DodajTreneraMenadzerForma
     */
    public TrenerMenadzerForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        popuniKomboSportova();
        popuniTabeluTreneri();
        
        btnKreiraj.setEnabled(true);
        btnSacuvajTrenera.setEnabled(false);
        btnOdustani.setEnabled(false);
        txtRBTrenera.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        txtPlata = new javax.swing.JTextField();
        cmbSport = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnOdustani = new javax.swing.JButton();
        btnKreiraj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTreneri = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtRBTrenera = new javax.swing.JTextField();
        btnSacuvajTrenera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jLabel4.setText("Plata:");

        jLabel5.setText("Sport:");

        cmbSport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Profil"));

        jLabel6.setText("Korisnicko ime:");

        jLabel7.setText("Korisnicka lozinka:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnKreiraj.setText("Kreiraj trenera");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Spisak zapamcenih trenera"));

        tblTreneri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTreneri);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );

        jLabel8.setText("RB. trenera:");

        btnSacuvajTrenera.setText("Sacuvaj trenera");
        btnSacuvajTrenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajTreneraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSacuvajTrenera, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIme)
                    .addComponent(txtPrezime)
                    .addComponent(cmbSport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPlata)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(txtRBTrenera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRBTrenera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvajTrenera, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        try {
            // TODO add your handling code here:
            int sifra = Controler.getInstanca().poslednjiRBTrenera();
            
            System.out.println("POSLEDNJI Trener: " + sifra);
            
            Trener trener = new Trener(sifra);
            Controler.getInstanca().obrisiTrenera(trener);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed

          try {
            btnKreiraj.setEnabled(false);
            Trener novi = new Trener();
            int broj = Controler.getInstanca().poslednjiRBTrenera();
            int RB = broj + 1;
              System.out.println("rb: " + RB);
            txtRBTrenera.setText("" + RB);
            novi.setSifraTrenera(RB);
            
            
            Trener trener = Controler.getInstanca().kreirajTrenera(novi);
            btnSacuvajTrenera.setEnabled(true);
            btnOdustani.setEnabled(true);
            if (trener != null){
                JOptionPane.showMessageDialog(this, "Sistem je uspesno kreirao novog trenera");
            }
            else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira novog trenera");

            }
            
        } catch (Exception ex) {
            Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
//        String ime = txtIme.getText();
//        String prezime = txtPrezime.getText();
//        String JMBG = txtJMBG.getText();
//        double plata = Double.parseDouble(txtPlata.getText());
//        Sport sport = (Sport) cmbSport.getSelectedItem();
//        String korisnickoIme = txtKorisnickoIme.getText();
//        String korisnickaLozinka = txtKorisnickaLozinka.getText();
//        Profil profil = new Profil(korisnickoIme, korisnickaLozinka);
//
//        Trener trener = new Trener(0, ime, prezime, JMBG, plata, true, profil, sport);
//
//        try {
//            if (!Controler.getInstanca().zapamtiProfil(profil)) {
//                JOptionPane.showMessageDialog(this, "Problem sa profilom");
//                return;
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(TrenerMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        boolean sacuvano = false;
//        try {
//            sacuvano = Controler.getInstanca().zapamtiTrenera(trener);
//        } catch (Exception ex) {
//            Logger.getLogger(TrenerMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (sacuvano) {
//            JOptionPane.showMessageDialog(this, "Trener je uspesno sacuvan");
//            txtIme.setText("");
//            txtPrezime.setText("");
//            txtJMBG.setText("");
//            txtPlata.setText("");
//            txtKorisnickoIme.setText("");
//            txtKorisnickaLozinka.setText("");
//        } else {
//            JOptionPane.showMessageDialog(this, "Trener nije sacuvan!");
//        }
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnSacuvajTreneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajTreneraActionPerformed
        
        String imeTrenera = txtIme.getText();
        String prezimeTrenera = txtPrezime.getText();
        String JMBGTrenera = txtJMBG.getText();
        double plataTrenera;
        try {
           plataTrenera = Double.parseDouble(txtPlata.getText());
           if(plataTrenera < 0){
               throw new Exception();
           }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unesi ispravnu platu!");
            return;

        }
        
        
        String korisnickoIme = txtKorisnickoIme.getText();
        String lozinka = txtPassword.getText();
        if(!imeTrenera.isEmpty() && !prezimeTrenera.isEmpty() && !JMBGTrenera.isEmpty() &&  plataTrenera > 0 && !korisnickoIme.isEmpty() && !lozinka.isEmpty()){
            try {
                
                if(JMBGTrenera.length() != 13){
                   JOptionPane.showMessageDialog(this, "JMBG mora imati tacno 13 cifara!");
                   return;

                }
                Sport sport = (Sport) cmbSport.getSelectedItem();
                
                int redniBroj = Controler.getInstanca().poslednjiRBTrenera();
                Profil profil = new Profil(korisnickoIme, lozinka);
                
                if (!Controler.getInstanca().zapamtiProfil(profil)) {
                    JOptionPane.showMessageDialog(this, "Problem sa profilom");
                    return;
                }
                
                
                Trener trener = new Trener(redniBroj, imeTrenera, prezimeTrenera, JMBGTrenera, plataTrenera, true, profil, sport);
                Trener t=null;
                try {
                    
                    
                    t = Controler.getInstanca().zapamtiTrenera(trener);
                    System.out.println("trener: " + t);
                } catch (Exception ex) {
                    Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(t != null){ 
                    ModelTabeleTreneri mttreneri = (ModelTabeleTreneri) tblTreneri.getModel();
                    mttreneri.dodajTrenera(t);
                    JOptionPane.showMessageDialog(this, "Sistem je uspesno zapamtio novog trenera!");
                    
                    btnSacuvajTrenera.setEnabled(false);
                    btnKreiraj.setEnabled(true);
                    btnOdustani.setEnabled(false);

                    txtIme.setText("");
                    txtPrezime.setText("");
                    txtJMBG.setText("");
                    txtPlata.setText("");
                    txtKorisnickoIme.setText("");
                    txtPassword.setText("");
                    
                    
                    
                   

                    
                }
                else {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti novog trenera");
                }
            } catch (Exception ex) {
                Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Unesi sve podatke!");
        }
    }//GEN-LAST:event_btnSacuvajTreneraActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvajTrenera;
    private javax.swing.JComboBox cmbSport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTreneri;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPlata;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtRBTrenera;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboSportova() {
        ArrayList<Sport> listaSportova = new ArrayList<>();
        cmbSport.removeAllItems();
        try {
            listaSportova = Controler.getInstanca().vratiSveSportove();
        } catch (Exception ex) {
            Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(listaSportova);
        for (IGeneralEntity sport : listaSportova) {
            cmbSport.addItem(sport);
        }
    }

    private void popuniTabeluTreneri() {
        ModelTabeleTreneri mtt = new ModelTabeleTreneri();
        tblTreneri.setModel(mtt);
    }

    
}
