/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Igrac;
import domen.Pozicija;
import domen.StatistikaIgracaSaUtakmice;
import domen.Tim;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Controler;
import domen.IGeneralEntity;
import domen.Trener;
import modeli.ModelTabeleIgraci;

/**
 *
 * @author duler
 */
public class UpisiIgracaUKlubMenadzerForma extends javax.swing.JDialog {

    /**
     * Creates new form UpisiIgracaUKlubMenadzerForma
     */
    public UpisiIgracaUKlubMenadzerForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        popuniKomboTim();
        popuniKomboPozicija();
        popuniTabeluIgraci();

        btnKreiraj.setEnabled(true);
        btnUpisiIgraca.setEnabled(false);
        btnOdustani.setEnabled(false);
        txtRBIgraca.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        chbDaLiJeKapiten = new javax.swing.JCheckBox();
        txtPlata = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JTextField();
        cmbTim = new javax.swing.JComboBox();
        cmbPozicija = new javax.swing.JComboBox();
        btnUpisiIgraca = new javax.swing.JButton();
        btnKreiraj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtRBIgraca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIgraci = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos novog igraca u klub"));

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jLabel4.setText("Plata:");

        jLabel5.setText("Da li je kapiten?");

        jLabel6.setText("Datum rodjenja:");

        jLabel7.setText("Tim:");

        jLabel8.setText("Pozicija:");

        cmbTim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTimItemStateChanged(evt);
            }
        });

        cmbPozicija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUpisiIgraca.setText("Upisi igraca");
        btnUpisiIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpisiIgracaActionPerformed(evt);
            }
        });

        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        jLabel9.setText("RB igraca:");

        txtRBIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRBIgracaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chbDaLiJeKapiten)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtRBIgraca)
                            .addComponent(cmbPozicija, javax.swing.GroupLayout.Alignment.LEADING, 0, 195, Short.MAX_VALUE)
                            .addComponent(cmbTim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlata, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIme, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnUpisiIgraca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtRBIgraca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chbDaLiJeKapiten)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpisiIgraca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Spisak zapamcenih igraca"));

        tblIgraci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIgraci);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTimItemStateChanged
        popuniKomboPozicija();

    }//GEN-LAST:event_cmbTimItemStateChanged

    private void btnUpisiIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpisiIgracaActionPerformed

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            String JMBG = txtJMBG.getText();
            double plata = Double.parseDouble(txtPlata.getText());
            boolean daLiJeKapiten = chbDaLiJeKapiten.isSelected();
            Date datum = sdf.parse(txtDatumRodjenja.getText());
            Tim tim = (Tim) cmbTim.getSelectedItem();
            Pozicija pozicija = (Pozicija) cmbPozicija.getSelectedItem();

            if (!ime.isEmpty() && !prezime.isEmpty() && !JMBG.isEmpty() && plata > 0) {
                
                if(JMBG.length() != 13){
                   JOptionPane.showMessageDialog(this, "JMBG mora imati tacno 13 cifara!");
                   return;

                }
                int redniBroj = 0;
                try {
                    redniBroj = Controler.getInstanca().poslednjiRBIgraca();
                } catch (Exception ex) {
                    Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
                }

                Igrac igrac = new Igrac(redniBroj, ime, prezime, JMBG, plata, daLiJeKapiten, datum, true, tim, pozicija);
                Igrac i = null;
                try {

                    i = Controler.getInstanca().zapamtiIgraca(igrac);
                    System.out.println("igrac: " + i);
                } catch (Exception ex) {
                    Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (i != null) {
                    ModelTabeleIgraci mtigraci = (ModelTabeleIgraci) tblIgraci.getModel();
                    mtigraci.dodajIgraca(i);
                    JOptionPane.showMessageDialog(this, "Sistem je uspesno zapamtio novog igraca!");

                    btnUpisiIgraca.setEnabled(false);
                    btnKreiraj.setEnabled(true);
                    btnOdustani.setEnabled(false);

                    txtIme.setText("");
                    txtPrezime.setText("");
                    txtJMBG.setText("");
                    txtPlata.setText("");
                    txtDatumRodjenja.setText("");

                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti novog igraca");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Unesi sve podatke");

            }

        } catch (ParseException ex) {
            Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Unesi datum u ispravnom formatu (dd.mm.yyyy)");
        } catch (NumberFormatException nex) {
            Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(Level.SEVERE, null, nex);
            JOptionPane.showMessageDialog(this, "Plata mora biti pozitivna!");
        }
    }//GEN-LAST:event_btnUpisiIgracaActionPerformed

    private void txtRBIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRBIgracaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRBIgracaActionPerformed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        try {
            btnKreiraj.setEnabled(false);
            Igrac novi = new Igrac();
            int broj = Controler.getInstanca().poslednjiRBIgraca();
            int RB = broj + 1;
            System.out.println("rb: " + RB);
            txtRBIgraca.setText("" + RB);
            novi.setSifraIgraca(RB);

            Igrac igrac = Controler.getInstanca().kreirajIgraca(novi);
            btnUpisiIgraca.setEnabled(true);
            btnOdustani.setEnabled(true);
            if (igrac != null) {
                JOptionPane.showMessageDialog(this, "Sistem je uspesno kreirao novog igraca");

            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira novog igraca");

            }

        } catch (Exception ex) {
            Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        try {
            // TODO add your handling code here:
            int sifra = Controler.getInstanca().poslednjiRBIgraca();

            System.out.println("POSLEDNJI Igrac: " + sifra);

            Igrac igrac = new Igrac(sifra);
            Controler.getInstanca().obrisiIgraca(igrac);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(KreirajNoviTimMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpisiIgracaUKlubMenadzerForma dialog = new UpisiIgracaUKlubMenadzerForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnUpisiIgraca;
    private javax.swing.JCheckBox chbDaLiJeKapiten;
    private javax.swing.JComboBox cmbPozicija;
    private javax.swing.JComboBox cmbTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIgraci;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPlata;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtRBIgraca;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboTim() {
        ArrayList<Tim> listaTimova = new ArrayList<>();
        try {
            listaTimova = Controler.getInstanca().vratiSveTimove();
        } catch (Exception ex) {
            Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbTim.removeAllItems();
        for (Tim tim : listaTimova) {
            cmbTim.addItem(tim);
        }
    }

    private void popuniKomboPozicija() {
        Tim t = (Tim) cmbTim.getSelectedItem();
        if (t != null) {
            ArrayList<Pozicija> listaPozicija = new ArrayList<>();
            try {
                listaPozicija = Controler.getInstanca().vratiPozicijeSporta(t.getTrener().getSport());
            } catch (Exception ex) {
                Logger.getLogger(UpisiIgracaUKlubMenadzerForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            cmbPozicija.removeAllItems();
            for (Pozicija pozicija : listaPozicija) {
                cmbPozicija.addItem(pozicija);
            }
        }

    }

    private void popuniTabeluIgraci() {
        ModelTabeleIgraci mti = new ModelTabeleIgraci();
        tblIgraci.setModel(mti);
    }
}
